### ISSUE TITLE
Doesn't work with latest Compose BOM 2025.07.00

### ISSUE THREAD

**Issue by Gaetano-Dati** [TuleSimon/xMaterialccp#25]
When trying to compile using the latest Compose BOM 2025.07.00 it shows this error:
`java.lang.NoSuchMethodError: No static method animateItemPlacement$default`

Try to fix it using the latest Compose BOM please

**Comment by TuleSimon** [comment]
Fixing, publishing new version in a momment

**Comment by TuleSimon** [comment]
@Gaetano-Dati  issue has been fixed and new version sent
